### PR TITLE
Add .NET 6 as target

### PR DESCRIPTION
**Pull request by silkfire**
I believe that this excellent library could benefit from getting its dependencies updated to the latest versions as well as adding the recently released .NET 6 as a TFM. This would also remove the need to depend on the NuGet package `System.Memory` for more recent .NET targets. Only .NET Standard and .NET Framework requires that dependency.

### CODE REVIEW

**Comment by silkfire** [comment]
@salarcode Is there any chance you could take a look at this PR?

**Comment by salarcode** [comment]
Sorry forgot about this PR;
You have basically changed the whole structure of project.
I think this is too much change... still looking

**Comment by salarcode** [comment]
I finally had time to have a proper look at this, I can say it is impressive work.
Even tough i'm not happy with the project structure change and some other things like namespace change which is very annoying; this kind of change is not aligned with commit guidances, I'm merging them anyway.

Thanks

**Comment by silkfire** [comment]
Hello again, I thought you had abandoned the project. You did not have to merge this, I realize that the changes were bigger than scoped for this PR and you can revert it to how it was before.

**Comment by salarcode** [comment]
I was just busy and forget about the project. I did amendments to your changes and now everything is good. The icon looks good too.
Thanks again.

**Comment by silkfire** [comment]
I understand, but there's a reason why I closed this PR as I no longer was interested in getting it merged. It was never the purpose to continue developing for the sake of this PR.

**Pull request merged**
